namespace CheminPayslip.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class refreshData : DbMigration
    {
        public override void Up()
        {
            CreateTable(
               "dbo.EmployeeDetails",
               c => new
               {
                   Id = c.Int(nullable: false, identity: true),
                   EmployeeId = c.Int(nullable: false),
                   Name = c.String(),
                   BASIC = c.Single(nullable: false),
                   DA = c.Single(nullable: false),
                   HRA = c.Single(nullable: false),
                   UMA = c.Single(nullable: false),
                   ARREAR = c.Single(nullable: false),
                   LAYOFF = c.Single(nullable: false),
                   STIPEND = c.Single(nullable: false),
                   SITE = c.Single(nullable: false),
                   LOCAL_CONVEY = c.Single(nullable: false),
                   DISTANCE = c.Single(nullable: false),
                   RESPONSIBILITY = c.Single(nullable: false),
                   PROJECT = c.Single(nullable: false),
                   FMA = c.Single(nullable: false),
                   ATTINC = c.Single(nullable: false),
                   COMPOFF = c.Single(nullable: false),
                   HARD = c.Single(nullable: false),
                   OT = c.Single(nullable: false),
                   VA = c.Single(nullable: false),
                   SITESTIPEND = c.Single(nullable: false),
                   FOODSITE = c.Single(nullable: false),
                   FOODHO = c.Single(nullable: false),
                   SPECIAL_RES_ALLOW = c.Single(nullable: false),
                   LEADERSHIP = c.Single(nullable: false),
                   HOUSE_RENT = c.Single(nullable: false),
                   TOTAL = c.Single(nullable: false),
                   PF = c.Single(nullable: false),
                   LIC = c.Single(nullable: false),
                   ESI = c.Single(nullable: false),
                   EXCESS_PAY = c.Single(nullable: false),
                   SALADV = c.Single(nullable: false),
                   EMERADV = c.Single(nullable: false),
                   MARRADV = c.Single(nullable: false),
                   MAXINS = c.Single(nullable: false),
                   INCOMETAX = c.Single(nullable: false),
                   DEDTOTAL = c.Single(nullable: false),
                   NETTOTAL = c.Single(nullable: false),
                   OT_HOURS = c.Single(nullable: false),
                   CLCR = c.Single(nullable: false),
                   CLT = c.Single(nullable: false),
                   CLBAL = c.Single(nullable: false),
                   MLCR = c.Single(nullable: false),
                   MLT = c.Single(nullable: false),
                   MLLBAL = c.Single(nullable: false),
                   ELCR = c.Single(nullable: false),
                   ELT = c.Single(nullable: false),
                   ELBAL = c.Single(nullable: false),
                   Date = c.String(),
                   CTC = c.Single(nullable: false),
                   Remarks = c.String(),
                   Place = c.String(),
                   OTHERDISBURSEMENT = c.String(),
                   ADVINSTNO = c.String(),
                   MADVINSTNO = c.String(),
                   BANKAC = c.String(),
                   BANKNAME = c.String(),
                   PFUAN = c.String(),
                   ESICODE = c.String(),
                   DESIGNATION = c.String(),
                   GRADE = c.String(),
                   SITE1DAYS = c.String(),
                   SITE2DAYS = c.String(),
                   SITE3DAYS = c.String(),
                   HODAYS = c.String(),
               })
               .PrimaryKey(t => t.Id);
            CreateTable(
               "dbo.EmployeeDetails2",
               c => new
               {
                   Id = c.Int(nullable: false, identity: true),
                   EmployeeId = c.Int(nullable: false),
                   Name = c.String(),
                   BASIC = c.Single(nullable: false),
                   DA = c.Single(nullable: false),
                   HRA = c.Single(nullable: false),
                   UMA = c.Single(nullable: false),
                   ARREAR = c.Single(nullable: false),
                   LAYOFF = c.Single(nullable: false),
                   STIPEND = c.Single(nullable: false),
                   SITE = c.Single(nullable: false),
                   LOCAL_CONVEY = c.Single(nullable: false),
                   DISTANCE = c.Single(nullable: false),
                   RESPONSIBILITY = c.Single(nullable: false),
                   PROJECT = c.Single(nullable: false),
                   FMA = c.Single(nullable: false),
                   ATTINC = c.Single(nullable: false),
                   COMPOFF = c.Single(nullable: false),
                   HARD = c.Single(nullable: false),
                   OT = c.Single(nullable: false),
                   VA = c.Single(nullable: false),
                   SITESTIPEND = c.Single(nullable: false),
                   FOODSITE = c.Single(nullable: false),
                   FOODHO = c.Single(nullable: false),
                   SPECIAL_RES_ALLOW = c.Single(nullable: false),
                   LEADERSHIP = c.Single(nullable: false),
                   HOUSE_RENT = c.Single(nullable: false),
                   TOTAL = c.Single(nullable: false),
                   PF = c.Single(nullable: false),
                   LIC = c.Single(nullable: false),
                   ESI = c.Single(nullable: false),
                   EXCESS_PAY = c.Single(nullable: false),
                   SALADV = c.Single(nullable: false),
                   EMERADV = c.Single(nullable: false),
                   MARRADV = c.Single(nullable: false),
                   MAXINS = c.Single(nullable: false),
                   INCOMETAX = c.Single(nullable: false),
                   DEDTOTAL = c.Single(nullable: false),
                   NETTOTAL = c.Single(nullable: false),
                   OT_HOURS = c.Single(nullable: false),
                   CLCR = c.Single(nullable: false),
                   CLT = c.Single(nullable: false),
                   CLBAL = c.Single(nullable: false),
                   MLCR = c.Single(nullable: false),
                   MLT = c.Single(nullable: false),
                   MLLBAL = c.Single(nullable: false),
                   ELCR = c.Single(nullable: false),
                   ELT = c.Single(nullable: false),
                   ELBAL = c.Single(nullable: false),
                   Date = c.String(),
                   CTC = c.Single(nullable: false),
                   Remarks = c.String(),
                   Place = c.String(),
                   OTHERDISBURSEMENT = c.String(),
                   ADVINSTNO = c.String(),
                   MADVINSTNO = c.String(),
                   BANKAC = c.String(),
                   BANKNAME = c.String(),
                   PFUAN = c.String(),
                   ESICODE = c.String(),
                   DESIGNATION = c.String(),
                   GRADE = c.String(),
                   SITE1DAYS = c.String(),
                   SITE2DAYS = c.String(),
                   SITE3DAYS = c.String(),
                   HODAYS = c.String(),
               })
               .PrimaryKey(t => t.Id);
            CreateTable(
               "dbo.EmployeeDetails3",
               c => new
               {
                   Id = c.Int(nullable: false, identity: true),
                   EmployeeId = c.Int(nullable: false),
                   Name = c.String(),
                   BASIC = c.Single(nullable: false),
                   DA = c.Single(nullable: false),
                   HRA = c.Single(nullable: false),
                   UMA = c.Single(nullable: false),
                   ARREAR = c.Single(nullable: false),
                   LAYOFF = c.Single(nullable: false),
                   STIPEND = c.Single(nullable: false),
                   SITE = c.Single(nullable: false),
                   LOCAL_CONVEY = c.Single(nullable: false),
                   DISTANCE = c.Single(nullable: false),
                   RESPONSIBILITY = c.Single(nullable: false),
                   PROJECT = c.Single(nullable: false),
                   FMA = c.Single(nullable: false),
                   ATTINC = c.Single(nullable: false),
                   COMPOFF = c.Single(nullable: false),
                   HARD = c.Single(nullable: false),
                   OT = c.Single(nullable: false),
                   VA = c.Single(nullable: false),
                   SITESTIPEND = c.Single(nullable: false),
                   FOODSITE = c.Single(nullable: false),
                   FOODHO = c.Single(nullable: false),
                   SPECIAL_RES_ALLOW = c.Single(nullable: false),
                   LEADERSHIP = c.Single(nullable: false),
                   HOUSE_RENT = c.Single(nullable: false),
                   TOTAL = c.Single(nullable: false),
                   PF = c.Single(nullable: false),
                   LIC = c.Single(nullable: false),
                   ESI = c.Single(nullable: false),
                   EXCESS_PAY = c.Single(nullable: false),
                   SALADV = c.Single(nullable: false),
                   EMERADV = c.Single(nullable: false),
                   MARRADV = c.Single(nullable: false),
                   MAXINS = c.Single(nullable: false),
                   INCOMETAX = c.Single(nullable: false),
                   DEDTOTAL = c.Single(nullable: false),
                   NETTOTAL = c.Single(nullable: false),
                   OT_HOURS = c.Single(nullable: false),
                   CLCR = c.Single(nullable: false),
                   CLT = c.Single(nullable: false),
                   CLBAL = c.Single(nullable: false),
                   MLCR = c.Single(nullable: false),
                   MLT = c.Single(nullable: false),
                   MLLBAL = c.Single(nullable: false),
                   ELCR = c.Single(nullable: false),
                   ELT = c.Single(nullable: false),
                   ELBAL = c.Single(nullable: false),
                   Date = c.String(),
                   CTC = c.Single(nullable: false),
                   Remarks = c.String(),
                   Place = c.String(),
                   OTHERDISBURSEMENT = c.String(),
                   ADVINSTNO = c.String(),
                   MADVINSTNO = c.String(),
                   BANKAC = c.String(),
                   BANKNAME = c.String(),
                   PFUAN = c.String(),
                   ESICODE = c.String(),
                   DESIGNATION = c.String(),
                   GRADE = c.String(),
                   SITE1DAYS = c.String(),
                   SITE2DAYS = c.String(),
                   SITE3DAYS = c.String(),
                   HODAYS = c.String(),
               })
               .PrimaryKey(t => t.Id);




        }

        public override void Down()
        {
        }
    }
}
