// <auto-generated />
namespace CheminPayslip.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addTableValid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTableValid));
        
        string IMigrationMetadata.Id
        {
            get { return "201807021231215_addTableValid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
